In [1]:
import pandas as pd

df = pd.read_csv("../dataset/processed/2023-2024.csv")

df.head()

,academic_year,college_code,college_name,branch_code,branch_name,status,section,category,stage,merit_rank,percentile
0,2023-2024,1002,"Government College of Engineering, Amravati",100219110,Civil Engineering,Government Autonomous,Home University,GOPENS,I,45820.0,80.732883
1,2023-2024,1002,"Government College of Engineering, Amravati",100219110,Civil Engineering,Government Autonomous,Home University,GSCS,I,54803.0,76.616654
2,2023-2024,1002,"Government College of Engineering, Amravati",100219110,Civil Engineering,Government Autonomous,Home University,GSTS,I,85528.0,58.742985
3,2023-2024,1002,"Government College of Engineering, Amravati",100219110,Civil Engineering,Government Autonomous,Home University,GVJS,I,53198.0,76.921342
4,2023-2024,1002,"Government College of Engineering, Amravati",100219110,Civil Engineering,Government Autonomous,Home University,GNT1S,I,55202.0,76.284368

In [2]:
df.shape

(23507, 11)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23507 entries, 0 to 23506
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   academic_year  23507 non-null  object
 1   college_code   23507 non-null  int64
 2   college_name   23507 non-null  object
 3   branch_code    23507 non-null  int64
 4   branch_name    23507 non-null  object
 5   status         23507 non-null  object
 6   section        23507 non-null  object
 7   category       23507 non-null  object
 8   stage          23507 non-null  object
 9   merit_rank     23012 non-null  float64
 10  percentile     23012 non-null  float64
dtypes: float64(2), int64(2), object(7)
memory usage: 2.0+ MB

In [4]:
df.isnull().sum()

academic_year      0
college_code       0
college_name       0
branch_code        0
branch_name        0
status             0
section            0
category           0
stage              0
merit_rank       495
percentile       495
dtype: int64

In [5]:
df.duplicated().sum()

0

In [6]:
df["academic_year"].value_counts()

academic_year
2023-2024    23507
Name: count, dtype: int64

In [7]:
df["section"].value_counts()

section
Home University                    9609
Other Than Home University         5767
Home University (Other Than HU)    5322
State Level                        2809
Name: count, dtype: int64

In [8]:
df["status"].value_counts()

status
Un-Aided                                               16551
Un-Aided Autonomous                                     2973
Government                                               713
Government-Aided Autonomous                              512
Government Autonomous                                    413
Un-Aided Autonomous Linguistic Minority - Hindi          369
Un-Aided Linguistic Minority - Hindi                     321
University Department                                    251
Un-Aided Religious Minority - Muslim                     216
University Autonomous                                    186
Un-Aided Religious Minority - Christian                  165
University Managed                                       116
Deemed University Autonomous                              93
Un-Aided Autonomous Linguistic Minority - Gujarathi       72
Un-Aided Religious Minority - Jain                        71
University Managed (Un-Aided)                             57
Un-Aided Linguistic Minority - Gujarathi                  55
Un-Aided Linguistic Minority - Gujarathi(Jain)            51
Un-Aided Linguistic Minority - Tamil                      46
Un-Aided Autonomous Linguistic Minority - Sindhi          44
Un-Aided Autonomous Religious Minority - Christian        39
Un-Aided Linguistic Minority - Sindhi                     36
Un-Aided Linguistic Minority - Malyalam                   27
Un-Aided Linguistic Minority - Gujar                      27
Un-Aided Autonomous Religious Minority - Jain             24
Un-Aided Religious Minority - Roman Catholics             23
Un-Aided Autonomous Linguistic Minority - Malyalam        22
Un-Aided Linguistic Minority - Punjabi                    17
University Managed Autonomous                             17
Name: count, dtype: int64

In [9]:
df["college_name"].nunique()

332

In [10]:
df["branch_name"].nunique()

80

In [11]:
df[df["college_name"].isnull()].head(20)

Empty DataFrame
Columns: [academic_year, college_code, college_name, branch_code, branch_name, status, section, category, stage, merit_rank, percentile]
Index: []

In [12]:
df[df["branch_name"].isnull()].head(20)

Empty DataFrame
Columns: [academic_year, college_code, college_name, branch_code, branch_name, status, section, category, stage, merit_rank, percentile]
Index: []

In [13]:
df = pd.read_csv("../dataset/processed/2023-2024.csv")

print(df.shape)
print(df.isnull().sum())

(23507, 11)
academic_year      0
college_code       0
college_name       0
branch_code        0
branch_name        0
status             0
section            0
category           0
stage              0
merit_rank       495
percentile       495
dtype: int64

In [14]:
df = pd.read_csv("../dataset/processed/2024-2025.csv")

print(df.shape)

print(df.isnull().sum())

(31257, 11)
academic_year      0
college_code       0
college_name       0
branch_code        0
branch_name        0
status             0
section            0
category           0
stage              0
merit_rank       725
percentile       725
dtype: int64

In [15]:
import pandas as pd

df23 = pd.read_csv("../dataset/processed/2023-2024.csv")
df24 = pd.read_csv("../dataset/processed/2024-2025.csv")
df25 = pd.read_csv("../dataset/processed/2025-2026.csv")

print(df23.shape, df24.shape, df25.shape)

(23507, 11) (31257, 11) (31257, 11)

In [16]:
print(df23.isnull().sum())
print(df24.isnull().sum())
print(df25.isnull().sum())

academic_year      0
college_code       0
college_name       0
branch_code        0
branch_name        0
status             0
section            0
category           0
stage              0
merit_rank       495
percentile       495
dtype: int64
academic_year      0
college_code       0
college_name       0
branch_code        0
branch_name        0
status             0
section            0
category           0
stage              0
merit_rank       725
percentile       725
dtype: int64
academic_year      0
college_code       0
college_name       0
branch_code        0
branch_name        0
status             0
section            0
category           0
stage              0
merit_rank       725
percentile       725
dtype: int64