In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../dataset/final/cleaned_dataset.csv")

df.shape

(84076, 11)

In [3]:
import sys
import os

project_root = os.path.abspath("..")

if project_root not in sys.path:
    sys.path.append(project_root)

In [14]:
from importlib import reload
import src.components.recommendation_engine as rec

reload(rec)

from src.components.recommendation_engine import RecommendationEngine

engine = RecommendationEngine(df)

In [5]:
engine.df.head()

,academic_year,college_code,college_name,branch_code,branch_name,status,section,category,stage,merit_rank,percentile
0,2023-2024,1002,"Government College of Engineering, Amravati",100219110,Civil Engineering,Government Autonomous,Home University,GOPENS,I,45820,80.732883
1,2023-2024,1002,"Government College of Engineering, Amravati",100219110,Civil Engineering,Government Autonomous,Home University,GSCS,I,54803,76.616654
2,2023-2024,1002,"Government College of Engineering, Amravati",100219110,Civil Engineering,Government Autonomous,Home University,GSTS,I,85528,58.742985
3,2023-2024,1002,"Government College of Engineering, Amravati",100219110,Civil Engineering,Government Autonomous,Home University,GVJS,I,53198,76.921342
4,2023-2024,1002,"Government College of Engineering, Amravati",100219110,Civil Engineering,Government Autonomous,Home University,GNT1S,I,55202,76.284368

In [6]:
branch_df = engine.filter_branch(
    "Computer Engineering"
)

branch_df.head()

,academic_year,college_code,college_name,branch_code,branch_name,status,section,category,stage,merit_rank,percentile
170,2023-2024,1012,"Government College of Engineering,Yavatmal",101224510,Computer Engineering,Government,Home University,GOPENH,I,31195,87.211312
171,2023-2024,1012,"Government College of Engineering,Yavatmal",101224510,Computer Engineering,Government,Home University,GSCH,I,45916,80.732883
172,2023-2024,1012,"Government College of Engineering,Yavatmal",101224510,Computer Engineering,Government,Home University,GSTH,I,69281,68.933782
173,2023-2024,1012,"Government College of Engineering,Yavatmal",101224510,Computer Engineering,Government,Home University,GVJH,I,31317,87.071832
174,2023-2024,1012,"Government College of Engineering,Yavatmal",101224510,Computer Engineering,Government,Home University,GNT1H,I,32367,86.696596

In [7]:
branch_df.shape

(11642, 11)

In [8]:
import os

print(os.getcwd())

c:\college predictor\notebook

In [9]:
import src.logger as lg

print(lg.LOG_FILE_PATH)

c:\college predictor\logs\06_30_2026_17_19_00.log

In [12]:
branch_df = engine.filter_branch(
    "Computer Engineering"
)

category_df = engine.filter_category(
    branch_df,
    "GOPENH"
)

category_df.shape

(460, 11)

In [15]:
branch_df = engine.filter_branch(
    "Computer Engineering"
)

category_df = engine.filter_category(
    branch_df,
    "GOPENH"
)

year_df = engine.filter_year(
    category_df,
    "2025-2026"
)

year_df.shape

(159, 11)

In [16]:
year_df[
    [
        "college_name",
        "branch_name",
        "category",
        "academic_year",
        "percentile"
    ]
].head(10)

,college_name,branch_name,category,academic_year,percentile
53763,"Government College of Engineering,Yavatmal",Computer Engineering,GOPENH,2025-2026,87.129889
55508,"Manav School of Engineering & Technology, Gut ...",Computer Engineering,GOPENH,2025-2026,70.872294
57522,Vilasrao Deshmukh Foundation Group of Institut...,Computer Engineering,GOPENH,2025-2026,67.844082
57599,Aditya Education Trust's Mitthulalji Sarada Po...,Computer Engineering,GOPENH,2025-2026,12.562027
57642,GRAMIN TECHNICAL AND MANAGEMENT CAMPUS NANDED.,Computer Engineering,GOPENH,2025-2026,57.253756
57813,STMEI's Sandipani Technical Campus-Faculty of ...,Computer Engineering,GOPENH,2025-2026,53.769478
58060,Jijau Institute of Engineering Technology and ...,Computer Engineering,GOPENH,2025-2026,0.492319
58062,Jijau Institute of Engineering Technology and ...,Computer Engineering,GOPENH,2025-2026,18.702808
58970,Manjara Charitable Trust's Rajiv Gandhi Instit...,Computer Engineering,GOPENH,2025-2026,95.715414
59222,"Thakur Shyamnarayan Engineering College, Mumbai",Computer Engineering,GOPENH,2025-2026,94.782972